instrumentation:
  root: source/patterns
  default-excludes: true
  excludes:
    - "**/*.spec.js"
  extensions:
    - .js
  variable: __coverage__
  es-modules: true
  include-all-sources: true
reporting:
  print: summary
  reports:
    - lcov
  dir: build/test/coverage