---
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - v6
sudo: false
before_script:
  - chmod +x build/scripts/run-travis-tests.sh
script:
  - ./build/scripts/run-travis-tests.sh