---
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - 9.3
sudo: false
before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
install:
  - yarn
  - yarn build:prod
before_script:
#  - npm install grunt-cli -g
  - chmod +x build/travis/10-tests.sh
script:
  - if [ "$TRAVIS_BRANCH" != "master" ]; then ./build/travis/10-tests.sh; fi
#  - grunt
before_deploy:
  - chmod +x build/travis/50-publish-npm-git.sh
  - chmod +x build/travis/55-deploy-aws.sh
  - if [ "$TRAVIS_BRANCH" = "master" ]; then ./build/travis/50-publish-npm-git.sh; fi
deploy:
  provider: s3
  access_key_id:
    secure: "E2a+khXn4FNZ1yDYYfpz2gsdyRK2m7BQMxHKI/q/+2eGmKTDlty8P9tVyMRm2IdgIZ24N5XVPNYq5+4Bgyc8564oi3ce/Wl5Zx7BDYNYcU7nc+MxIiEHbC6aKei1ayhQ1CiNHtVLheTwmDNxndBI1GaU6neW+2vxErAjX65VQxOeBEc4sqydf0U1r38ojSFVZxP++RrDv0l1/0PuDm8DG3ZXkEvRAI2E/kRppF8LQaPEYctZqhQi3zrqiq5y0gL2BV1e2urW3F3z+kc+AAgLyNy7ZinqB9EPXp+6rSKTiMwtimeX+xcPGzvR+bbk2UQiFoKkcPSsS48yXoG/kAxZqFDXU8yw+jXHNrNtrgUF1mSvzmWSoP5cPURwvTMFyN+v2TKJDx0Q+xNKIwzduy2XKjQQnrOc6f+9vChQjh19O+FpnLkrjkIYDZV4HtnhpxdbMaBMUlX1znLaL0Ut4iTAWZopLSrYlSKMP/Cv+qiqqLui0xuSjXgGcNGq5DPjR0ZYZ2xpypXKwIRXXsThTuoDATWD864P50R/AOP0sFgdxwmUEDQIiqWW0YLmkkaINfNUois/0mcFg5cFOhc6hOHQBFOIDILjduEKyx8TFh9QwvhdtdC+BZbUa4p5vfFNQACrAT9FoiMUaWlKj1Elgtn9EIEFPJacYoEUB+7ML5dT+2w="
  secret_access_key:
    secure: "QGvQ9vS7j70nKYGYCzLNL2OhnQIXyCWCZjK4kIuo3BtgnWt86T/mQReVqXKgfFl8dzZmy+ifOKpO18OHfrQtkd2NhWulLC5eYnMRYWZFfzXfppp/x5ULiZLQ1+7mltGmJfl5HQZXSlk+UQmvxz87bW1gYTZPOUH6oH4+MwcWN1HauVCH47HbGTKS+DGOjslRAAWS8zl1O3HzCidJuutlBjKX/Uys6mwWoWu86i/SCyqnbiu3vBf2J/qbxkek30k/3O0/Z66/lmhCIXZLfAsoA6soFbyRLKtvvn5eJ82QerYOICL/2kNmeGmViSPob8jmEtx11i+7hE6DOSANdzQH7vXOeS71n85mM94UuulCRrWheYzJN+peBVcJSptCRoblukUB1O/+W9Nmb6dKzGhwpP/8MJbuchPXJWv4W25CpBhLd9dD/vpaOYJV5EVRas/i2bKYgES9819oru8y2eE5ABTCdo58Sd19kOEVw0E3ZSZRY1nv1HEZQTAwZ9X2utKYEuU1m2qStx++IX7dAp2Avf2Cvo9JenjAZADrxFCtPk1HmKdjjjdhMFPqwn1duzmXLdzN3cyqOp2BbfAdp3qYJy0giENWPrYmP4MJVcZ1DS2EyPZoSTdSBZ86qh66vGU1+UvcsCNgSS7nN6rtfxaYYOuT41E9S8lzf2GR+FBEzPk="
  bucket: "aa-documentation"
  skip_cleanup: true
  region: eu-central-1
  local_dir: dist
  upload-dir: docs/2.2
  on:
    branch: master
after_deploy:
  - if [ "$TRAVIS_BRANCH" = "master" ]; then DIST_ID=${CF_DISTRIBUTION} KEY=${AWS_ACCESS_KEY} SECRET=${AWS_SECRET_KEY} ./build/travis/55-deploy-aws.sh; fi
env:
  global:
  # Those are the variables of the after_deploy script in corresponding order
    - secure: "cebbDtbpnEiWEXmLdefpycs0eHJsGOrN3h+y4IlnN/qDxX6L8sPRfbotcOKNWd3M2tgi+GODc4Vbk7tkUp60oyKiZo28pNfftySCRdmS7dk2DIy3L9Zn4S8he+r2Sdy/ZXzZcU/gsyM/fywQtRGNoZLAQATdJpAGTW3K9bw9ATzk2CEjI2WxAwfdmT572GtGKvJ1u5PSO1uS6tjhdFklmlakmjQUKKTs7Jt0RwrhzGIl7hBXGXa9V6l00HGjV1s2fnFA7VsQUIwcTEioYGLBeu76yMvgegLEdJ0KGgN19lK4S8Dbfgvizdwvp8DmlXVRfXHn5Qv0Oc2xXXea0/piTztK031XV8ggYU0i1tqy04wj63V/aMVuDS8M3jbo31mJPwC5gUyS1gwyLP860/WZrulc7CQgZj3mw83x7p2h3I0jDGZVKR4se+/NROR7L8iEaGGk2Jgor4qJA3fgbT6H5yBjqIEcUa8C9kH5G9xARt4zGtBq05PCqulhm/n/4lBMM6V3CM47r/aUlhRlGaxtbUrbHAYBwae9UkG4fw+C0aW2N1r17RXh00SHtRB8RiAmAJWmqQw3rGBOuo16ffDPr2dCQkSxXrhp9bBpK4I5cdyDPLAEuxg3+RYoJEj5SPgpYaYrWMlJQtRXHfVqzogGYmKWJxNFznqT11/tINq2nIw="
    - secure: "vxPeGmCMTLueS6aG9DI7ljfhMPL6LqGREsnFWvmzt0repSlqUjxclOeqiy3ZWsucoYk4fMe2mACmr2GqEfdWiPrqYZohF5ilN4Sk5dItKmSQcKiO2Vs98slZ8jzkrdw7tnfAryJlxfiUbnQZEdoiv33RF1uU/JxPj4kQ1Dyy42w57XXHWQ/MeZtp+4wsGCJ+gATOJtgD/pWppbaH50ZgkQgHOEkzn52sUzdtVFb23DtOS1NqrUNcjEx11m2lU72kAzdWd2oeF0A+EXjWNd36JnVeWRab9AGnEVNekZhcxAdnUWDceKpQ/W/+26t7u4sfuidsVwU7ljIFHTPeEBHd15I5eSsdbjWlx7ZZjxAcu+0Hb4RrU4nnk0dDA48cxYf5zTKP/c7n4FsXLXduTdKxpDmv2qdYXycyfT/FzZ0bKGWw3nczYW/0s8jwaIbRar6bFV3QmyqJMOm2Y2Z4gCHtZ0T98hj8M9WTuq/HvSrp20BEUp9yPz0djZXoBXqfUAG+OiqrU6SuIlR68A76lmAoyzZ5zY5TZtSOP2IsAlyc/NjYKpB8no9pTaeMCn52RYT2JeBRBZCp9OJb8ZNDKGnjEACg0NhazQGfsI82CNakTnbFAzRo2IvMDuGs66+AHcZXeY6d+eZDRIveM+bSS3nDG61rKhYB4w9kt3P+UZHpPqU="
    - secure: "eU+aiQhxHKcvZfO7Apw6IifRw6+T25UAbtKa7uAx5W7Ew2Lhoy40WctePa+AIiiyAxqommZFyszqpE3Q2Vgv5hevATs2BxnGQhpZHXhKnUpAob2vrgnc3ps39ieayn/auztGoTuWJId7AsXkJJ+QG2bnZ/EbAjcZEN9CqUFfmolKleAdMDeGHMYGD/HPGl3ksaUOFauMG8RihV72k6E4mXkqDMSQ0A/zjJgCBBUp9LIzN6Ge4Pwp5CceYkhQxPn46oLx5RXxLIPDjlodaBo9OmrAbFuj2OB0HVRyL+3he8ZZizr21aL3eLEeNBESMF7KCJFq9TJOqthplUpsbBzrV3PEhcHMFlzVzxLjBit0HliWhxWPciJcI2rQZod0pTanTnUAZWw7pB4RFvqJOqdgmBwOtmTD9XnQj8srEpk/NbeA1Z9C8htQXZLY3cWc5UV8ZoxU8x2Y4HEA2MZOsdozkQlLNbVZ6RwEZW8RHcLRu0cL9nHzGug3iu8wtT95oqO1K9jbEwPG+PvhKWlqE6HyXIFGp0FRvhJCmV5gdMt2H86jWuLs7OO3PpwOY3gdHwmoEda+R4Ndt6GZ2qbnOVa9lsHHB4ab5/4hsNvKcIXJuyU0QFU/C3JIjloqpNr9EPac3NV6FyYgq4rzbZeGzeHV7z8kU2zrqzQ47u4wd1fkjKM="