---
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - "stable"
sudo: false
before_install:
  - chmod +x build/scripts/run-travis-tests.sh
script:
  - ./build/scripts/run-travis-tests.sh