---
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - 8
sudo: false
before_install:
  - chmod +x build/scripts/install-travis-depedencies.sh
install:
  - ./build/scripts/install-travis-depedencies.sh
before_script:
  - chmod +x build/scripts/run-travis-tests.sh
script:
  - ./build/scripts/run-travis-tests.sh