/* To avoid CSS expressions while still supporting IE 7 and IE 6, use this script */
/* The script tag referencing this file must be placed before the ending body tag. */

/* Use conditional comments in order to target IE 7 and older:
	<!--[if lt IE 8]><!-->
	<script src="ie7/ie7.js"></script>
	<!--<![endif]-->
*/

(function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'app-arena-website\'">' + entity + '</span>' + html;
	}
	var icons = {
		'aa-icon-arrow-down': '&#xe901;',
		'aa-icon-arrow-left': '&#xe902;',
		'aa-icon-arrow-up': '&#xe903;',
		'aa-icon-balance-scale': '&#xe904;',
		'aa-icon-bar-chart': '&#xe905;',
		'aa-icon-bell': '&#xe906;',
		'aa-icon-bolt-o': '&#xe907;',
		'aa-icon-bolt': '&#xe908;',
		'aa-icon-box': '&#xe909;',
		'aa-icon-browser-plus': '&#xe90a;',
		'aa-icon-brush': '&#xe90b;',
		'aa-icon-calendar': '&#xe90f;',
		'aa-icon-caret-down': '&#xe910;',
		'aa-icon-caret-left': '&#xe911;',
		'aa-icon-caret-right': '&#xe912;',
		'aa-icon-caret-up': '&#xe913;',
		'aa-icon-circle-o-notch': '&#xe914;',
		'aa-icon-clipboard': '&#xe915;',
		'aa-icon-cog-star': '&#xe916;',
		'aa-icon-colors': '&#xe917;',
		'aa-icon-comment-text': '&#xe918;',
		'aa-icon-comment': '&#xe919;',
		'aa-icon-crop': '&#xe91a;',
		'aa-icon-css': '&#xe91b;',
		'aa-icon-customer': '&#xe91c;',
		'aa-icon-desktop': '&#xe91d;',
		'aa-icon-domain': '&#xe91e;',
		'aa-icon-dot-circle-o': '&#xe920;',
		'aa-icon-ellipsis': '&#xe921;',
		'aa-icon-facebook-app': '&#xe922;',
		'aa-icon-facebook-apps': '&#xe923;',
		'aa-icon-facebook': '&#xe925;',
		'aa-icon-flag-checkered': '&#xe926;',
		'aa-icon-floppy': '&#xe927;',
		'aa-icon-gallery': '&#xe928;',
		'aa-icon-github': '&#xe929;',
		'aa-icon-globe-filled': '&#xe92c;',
		'aa-icon-globe': '&#xe92d;',
		'aa-icon-google-plus': '&#xe92f;',
		'aa-icon-graduation-cap': '&#xe930;',
		'aa-icon-html': '&#xe932;',
		'aa-icon-image': '&#xe933;',
		'aa-icon-key': '&#xe934;',
		'aa-icon-lightbulb': '&#xe935;',
		'aa-icon-like-plus': '&#xe936;',
		'aa-icon-link': '&#xe937;',
		'aa-icon-list': '&#xe938;',
		'aa-icon-mail': '&#xe939;',
		'aa-icon-mobile-check': '&#xe93a;',
		'aa-icon-mobile': '&#xe93b;',
		'aa-icon-multi-select': '&#xe93c;',
		'aa-icon-newsletter': '&#xe93d;',
		'aa-icon-paper-plane-o': '&#xe93e;',
		'aa-icon-plug': '&#xe93f;',
		'aa-icon-pointer': '&#xe940;',
		'aa-icon-popularity': '&#xe941;',
		'aa-icon-question-circle-filled': '&#xe942;',
		'aa-icon-question-circle': '&#xe943;',
		'aa-icon-refresh': '&#xe944;',
		'aa-icon-scale': '&#xe945;',
		'aa-icon-select': '&#xe946;',
		'aa-icon-share': '&#xe947;',
		'aa-icon-stadion': '&#xe948;',
		'aa-icon-tablet': '&#xe949;',
		'aa-icon-target': '&#xe94a;',
		'aa-icon-text': '&#xe94b;',
		'aa-icon-thumbs-o-up': '&#xe94c;',
		'aa-icon-thumbs': '&#xe94d;',
		'aa-icon-ticket': '&#xe94e;',
		'aa-icon-time-filter': '&#xe94f;',
		'aa-icon-tool': '&#xe950;',
		'aa-icon-trash': '&#xe951;',
		'aa-icon-trophy': '&#xe952;',
		'aa-icon-twitter': '&#xe953;',
		'aa-icon-two-users': '&#xe954;',
		'aa-icon-user-minus': '&#xe955;',
		'aa-icon-user-refresh': '&#xe956;',
		'aa-icon-user-up': '&#xe957;',
		'aa-icon-whatsapp': '&#xe958;',
		'aa-icon-youtube': '&#xe959;',
		'aa-icon-browser': '&#xe900;',
		'aa-icon-bullhorn': '&#x1f4ef;',
		'aa-icon-chart': '&#x1f4c9;',
		'aa-icon-check': '&#x2714;',
		'aa-icon-chevron-down': '&#x2304;',
		'aa-icon-chevron-left': '&#x2039;',
		'aa-icon-chevron-right': '&#x203a;',
		'aa-icon-chevron-up': '&#x2c4;',
		'aa-icon-circle': '&#x20dd;',
		'aa-icon-close': '&#x2297;',
		'aa-icon-cloud-upload': '&#x2601;',
		'aa-icon-cog': '&#x2699;',
		'aa-icon-comment-chart': '&#xe90c;',
		'aa-icon-digital-chart': '&#xe90d;',
		'aa-icon-download': '&#xe90e;',
		'aa-icon-exclamation-circle': '&#xfe57;',
		'aa-icon-external-link': '&#x1f517;',
		'aa-icon-eye': '&#x1f440;',
		'aa-icon-file-pdf': '&#x1f4c2;',
		'aa-icon-file': '&#x1f4c1;',
		'aa-icon-flag': '&#x2691;',
		'aa-icon-grid-full': '&#xa81f;',
		'aa-icon-grid-two': '&#x25e8;',
		'aa-icon-heart-filled': '&#x2665;',
		'aa-icon-heart': '&#x2661;',
		'aa-icon-info-circle': '&#x2139;',
		'aa-icon-label': '&#xe0023;',
		'aa-icon-line-chart': '&#x1f4b9;',
		'aa-icon-lock': '&#x1f512;',
		'aa-icon-log-in': '&#x20ef;',
		'aa-icon-log-out': '&#x20ee;',
		'aa-icon-menu-circle': '&#xe91f;',
		'aa-icon-minus': '&#x208b;',
		'aa-icon-mouse-click': '&#x298;',
		'aa-icon-pencil-circle': '&#x2710;',
		'aa-icon-pencil': '&#x270e;',
		'aa-icon-play-circle': '&#xe924;',
		'aa-icon-plus': '&#x2295;',
		'aa-icon-responsive': '&#x1f4bb;',
		'aa-icon-search-circle': '&#x1f50e;',
		'aa-icon-search': '&#x1f50d;',
		'aa-icon-shield': '&#x101db;',
		'aa-icon-sort-amount-asc': '&#xe92a;',
		'aa-icon-sort-amount-desc': '&#xe92b;',
		'aa-icon-star': '&#x2605;',
		'aa-icon-time': '&#x1f553;',
		'aa-icon-upload': '&#xe92e;',
		'aa-icon-user-circle': '&#x1f471;',
		'aa-icon-user': '&#x1f64e;',
		'aa-icon-users': '&#xe931;',
		'aa-icon-slider-arrow-left': '&#x2b9c;',
		'aa-icon-slider-arrow-right': '&#x2b9e;',
		'aa-icon-arrow-right': '&#x2192;',
		'aa-icon-arrow-right-circle': '&#x21e2;',
		'aa-icon-Neue_Nutzerdaten_generieren_fill': '&#x1f4ca;',
		'aa-icon-aa-analytics': '&#x1f4c8;',
		'0': 0
		},
		els = document.getElementsByTagName('*'),
		i, c, el;
	for (i = 0; ; i += 1) {
		el = els[i];
		if(!el) {
			break;
		}
		c = el.className;
		c = c.match(/aa-icon-[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
}());
