export const priceSelectorContainer: string;
export const serviceHours: string;
export const serviceHourNumber: string;
export const priceServicePrompt: string;
export const priceHeader: string;
export const taxHint: string;
export const header: string;
export const purchaseButton: string;
export const pulse: string;
